import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
const route=await readFile('app/api/admin/balance/[...path]/route.ts','utf8');
const validation=await readFile('lib/balance-validation.ts','utf8');
const api=await readFile('lib/balance-api.ts','utf8');
const patch=await readFile('components/ops/balance/PatchStudio.tsx','utf8');
test('balance BFF requires signed session and constrains path segments',()=>{assert.match(route,/assertAdmin\(\)/);assert.match(route,/SAFE_SEGMENT/);assert.match(route,/\/v1\/admin\/balance\//);assert.match(route,/part!=='\.\.'/)});
test('writes use CSRF origin checking and imports are JSON capped at one MB',()=>{assert.match(route,/sameOrigin\(req\)/);assert.match(route,/application\/json/);assert.match(route,/IMPORT_LIMIT/);assert.match(validation,/1024 \* 1024/)});
test('admin key remains server-only',async()=>{for(const dir of ['components','lib']){const files=await readdir(dir,{recursive:true});for(const file of files.filter(x=>/\.(tsx?|jsx?)$/.test(x))){const source=await readFile(`${dir}/${file}`,'utf8');if(`${dir}/${file}`!=='lib/backend-proxy.ts')assert.doesNotMatch(source,/BACKEND_ADMIN_API_KEY/);}}assert.match(route,/process\.env\.BACKEND_ADMIN_API_KEY/);assert.doesNotMatch(route,/NEXT_PUBLIC/)});
test('hero and ability validation covers finite damage and per-level arrays',()=>{assert.match(validation,/Number\.isFinite/);assert.match(validation,/damageMin>stats\.damageMax/);assert.match(validation,/value\.length === maxLevel/)});
test('client handles row conflicts and workflow restricts publish',()=>{assert.match(api,/response\.status===401/);assert.match(patch,/rowVersion:fresh\.rowVersion/);assert.match(patch,/Type \$\{fresh\.version\} to publish/);assert.match(validation,/approved.*schedule.*publish/)});
test('public patches exclude draft and non-production data',async()=>{const source=await readFile('components/PublicPatches.tsx','utf8');assert.match(source,/published.*superseded/);assert.match(source,/releaseChannel==='production'/);assert.doesNotMatch(source,/actorId|requestId|audit/i)});
