'use client';
import { useCallback,useEffect,useState } from 'react';
import { Card,Shell } from '@/components/Shell';
import { useLocale } from '@/components/LocaleProvider';
import type { MatchHistoryEntry } from '@/lib/match-types';
type Profile={personaName?:string;avatarUrl?:string;profileUrl?:string;trustRating?:number;rating?:number;trustScore?:number;preferredRole?:string;preferredRegions?:string[]};
type Filter='all'|'victory'|'defeat'|'cancelled';
export default function ProfilePage(){const {locale,t,number}=useLocale();const [profile,setProfile]=useState<Profile|null>(null);const [matches,setMatches]=useState<MatchHistoryEntry[]>([]);const [filter,setFilter]=useState<Filter>('all');const [page,setPage]=useState(1);const [hasMore,setMore]=useState(false);const [status,setStatus]=useState<'loading'|'ready'|'offline'|'empty'>('loading');const load=useCallback(async()=>{setStatus('loading');try{const [me,history]=await Promise.all([fetch('/api/backend/me',{cache:'no-store',credentials:'include'}),fetch(`/api/backend/me/matches?page=${page}&limit=10&result=${filter}`,{cache:'no-store',credentials:'include'})]);if(!me.ok||!history.ok)throw new Error();const a=await me.json(),b=await history.json();setProfile(a.player);const rows=Array.isArray(b.matches)?b.matches:[];setMatches(rows);setMore(Boolean(b.hasMore??b.nextPage));setStatus(rows.length?'ready':'empty')}catch{setStatus('offline')}},[page,filter]);useEffect(()=>{void load()},[load]);
 if(!profile&&status!=='loading')return <Shell><Card><h1 className="text-3xl font-black">{status==='offline'?t('offline'):t('sessionExpired')}</h1><button onClick={()=>void load()} className="primary mt-4">Retry</button></Card></Shell>;
 return <Shell><div className="grid gap-6"><Card>{profile&&<div className="flex flex-wrap items-center gap-4"><img src={profile.avatarUrl||'/avatar-fallback.svg'} alt="" className="h-24 w-24 rounded-3xl"/><div className="flex-1"><h1 className="text-4xl font-black">{profile.personaName}</h1><a href={profile.profileUrl} target="_blank" rel="noreferrer" className="text-trust-soft">{t('steamProfile')}</a></div><Stat label="TRUST Rating" value={number(profile.trustRating??profile.rating??0)}/><Stat label="Trust Score" value={number(profile.trustScore??0)}/></div>}</Card><Card><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-3xl font-black">{t('history')}</h2><div role="group" className="flex flex-wrap gap-2">{(['all','victory','defeat','cancelled'] as const).map(f=><button aria-pressed={filter===f} className={filter===f?'primary':'rounded-xl bg-white/5 px-4 py-2'} onClick={()=>{setFilter(f);setPage(1)}} key={f}>{locale==='ru'?({all:'Все',victory:'Победы',defeat:'Поражения',cancelled:'Отменённые'}[f]):f}</button>)}</div></div>{status==='loading'&&<div className="mt-4 animate-pulse motion-reduce:animate-none rounded-2xl bg-white/10 p-8">{t('loading')}</div>}{status==='offline'&&<p role="alert" className="mt-4">{t('offline')} <button onClick={()=>void load()} className="underline">Retry</button></p>}{status==='empty'&&<p className="mt-4 text-zinc-400">{t('noMatches')}</p>}{status==='ready'&&matches.map(m=><article key={m.id} className="mt-3 grid gap-2 rounded-2xl bg-white/5 p-4 sm:grid-cols-7"><b>{m.roomCode||m.id}</b><span>{m.result||m.status}</span><span>{m.region||'—'}</span><span>{m.userTeam||'—'}</span><span>{m.radiantScore??'—'}:{m.direScore??'—'}</span><span>{m.durationSeconds===undefined?'—':`${Math.floor(m.durationSeconds/60)}m`}</span><span>{m.ratingDelta===undefined?'—':`${m.ratingDelta>0?'+':''}${m.ratingDelta}`} / {m.trustScoreDelta===undefined?'—':`${m.trustScoreDelta>0?'+':''}${m.trustScoreDelta}`}</span></article>)}<div className="mt-5 flex justify-between"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>←</button><span>{page}</span><button disabled={!hasMore} onClick={()=>setPage(p=>p+1)}>→</button></div></Card></div></Shell>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-white/5 p-4"><small>{label}</small><p className="text-xl font-black">{value}</p></div>}
