'use client';
import { createContext, useCallback, useContext, useEffect, useRef, useState } from 'react';
import { CheckCircle2, Loader2, Play, RotateCcw, ShieldAlert, Swords, WifiOff } from 'lucide-react';
import { useRuntimeConfig } from '@/components/useRuntimeConfig';
import { useLocale } from '@/components/LocaleProvider';
import type { MatchDetails, MatchPlayer, MatchStatus, MeState } from '@/lib/match-types';

type Phase = MatchStatus|'empty'|'loading'|'offline'|'unauthorized'|'disabled'|'error';
type Context = { phase:Phase; match:MatchDetails|null; regions:string[]; primaryRole:string; searchSeconds:number; acceptCountdown:number; busy:boolean; lastError:string; toggleRegion:(v:string)=>void; setPrimaryRole:(v:string)=>void; startSearch:()=>void; cancelSearch:()=>void; acceptMatch:()=>void; declineMatch:()=>void; startConnection:()=>void; connectionReady:()=>void; refresh:()=>void; reset:()=>void; resetDemo:()=>void };
const MatchmakingContext=createContext<Context|null>(null);
const validStatuses=new Set<MatchStatus>(['idle','searching','accepting','ready','connecting','in_progress','completed','cancelled']);
const asPlayers=(value:unknown,team:'radiant'|'dire'):MatchPlayer[]=>Array.isArray(value)?value.map((raw,index)=>{const p=(raw&&typeof raw==='object'?raw:{}) as Record<string,unknown>;return {id:String(p.id??p.playerId??`${team}-${index}`),steamId64:p.steamId64 as string|undefined,personaName:String(p.personaName??p.name??p.nickname??`Player ${index+1}`),avatarUrl:p.avatarUrl as string|undefined,profileUrl:p.profileUrl as string|undefined,role:String(p.role??'—'),trustRating:Number(p.trustRating??p.rating??0),team,isBot:p.isBot===true,acceptStatus:String(p.acceptStatus??p.accept_status??'pending') as MatchPlayer['acceptStatus'],connectionStatus:(p.isBot===true?'connected':String(p.connectionStatus??p.connection_status??'pending')) as MatchPlayer['connectionStatus'],ratingBefore:Number.isFinite(Number(p.ratingBefore))?Number(p.ratingBefore):undefined,ratingAfter:Number.isFinite(Number(p.ratingAfter))?Number(p.ratingAfter):undefined,trustScoreBefore:Number.isFinite(Number(p.trustScoreBefore))?Number(p.trustScoreBefore):undefined,trustScoreAfter:Number.isFinite(Number(p.trustScoreAfter))?Number(p.trustScoreAfter):undefined}}):[];
export function normalizeMatchDetails(payload:unknown,id?:string):MatchDetails|null{if(!payload||typeof payload!=='object')return null;const root=payload as Record<string,unknown>;const raw=((root.match&&typeof root.match==='object')?root.match:root) as Record<string,unknown>;const teams=(raw.teams&&typeof raw.teams==='object'?raw.teams:{}) as Record<string,unknown>;const players=Array.isArray(raw.players)?raw.players:[];const radiant=asPlayers(teams.radiant??raw.radiant??players.filter(p=>String((p as Record<string,unknown>).team).toLowerCase()==='radiant'),'radiant');const dire=asPlayers(teams.dire??raw.dire??players.filter(p=>String((p as Record<string,unknown>).team).toLowerCase()==='dire'),'dire');const status=String(raw.status??root.status??'idle') as MatchStatus;return {id:String(raw.id??raw.matchId??id??''),status:validStatuses.has(status)?status:'idle',roomCode:raw.roomCode as string|undefined,region:raw.region as string|undefined,teams:{radiant,dire},accepted:Number(raw.accepted??raw.acceptedPlayers??[...radiant,...dire].filter(p=>p.acceptStatus==='accepted').length),required:Number(raw.required??raw.requiredPlayers??radiant.length+dire.length),acceptDeadline:(raw.acceptDeadline??raw.accept_deadline) as string|undefined,inProgressAt:raw.inProgressAt as string|undefined,completedAt:raw.completedAt as string|undefined,cancelledAt:raw.cancelledAt as string|undefined,winner:raw.winner as MatchDetails['winner'],radiantScore:num(raw.radiantScore),direScore:num(raw.direScore),durationSeconds:num(raw.durationSeconds??raw.duration),cancellationReason:(raw.cancellationReason??raw.reason) as string|undefined,cancellationCode:raw.cancellationCode as string|undefined,requeued:raw.requeued===true,currentPlayerId:(root.playerId??raw.currentPlayerId) as string|undefined,timeline:Array.isArray(raw.timeline)?raw.timeline as MatchDetails['timeline']:undefined};}
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):undefined;
async function request(path:string,init:RequestInit={},signal?:AbortSignal){const response=await fetch(path,{...init,cache:'no-store',credentials: 'include',headers:{'Content-Type':'application/json',...init.headers},signal});const text=await response.text();let data:unknown={};try{data=text?JSON.parse(text):{};}catch{}if(!response.ok){const d=data as Record<string,unknown>;throw Object.assign(new Error(String((d.error as Record<string,unknown>)?.code??d.code??d.message??'REQUEST_FAILED')),{status:response.status});}return data;}
export function statusFromState(payload:unknown):{status:MatchStatus;match:MatchDetails|null}{const data=(payload&&typeof payload==='object'?payload:{}) as Record<string,unknown>;const state=((data.state&&typeof data.state==='object')?data.state:data) as Record<string,unknown>;const match=normalizeMatchDetails(state.match??data.match);const status=String(state.status??state.matchStatus??match?.status??(state.queue?'searching':'idle')) as MatchStatus;return {status:validStatuses.has(status)?status:'idle',match};}
export function secondsUntil(deadline?:string,now=Date.now()){return deadline?Math.max(0,Math.ceil((new Date(deadline).getTime()-now)/1000)):0;}
export function MatchmakingProvider({children}:{children:React.ReactNode}){const [regions,setRegions]=useState(['EU West']);const [primaryRole,setRole]=useState('Mid');const [phase,setPhase]=useState<Phase>('loading');const [match,setMatch]=useState<MatchDetails|null>(null);const [searchSeconds,setSearchSeconds]=useState(0);const [acceptCountdown,setCountdown]=useState(0);const [busy,setBusy]=useState(false);const [lastError,setError]=useState('');const controller=useRef<AbortController|null>(null);const config=useRuntimeConfig();
 useEffect(()=>{try{const r=JSON.parse(localStorage.getItem('trust-regions')||'[]');if(Array.isArray(r)&&r.length)setRegions(r.slice(0,3));}catch{}setRole(localStorage.getItem('trust-primary-role')||'Mid');},[]);
 const refresh=useCallback(async()=>{controller.current?.abort();const c=new AbortController();controller.current=c;try{const payload=await request('/api/backend/me/state',{},c.signal);const next=statusFromState(payload);setPhase(next.status);setMatch(next.match);setError('');}catch(e){if((e as Error).name==='AbortError')return;setError(e instanceof Error?e.message:'REQUEST_FAILED');setPhase((e as {status?:number}).status===401?'unauthorized':'offline');}},[]);
 useEffect(()=>{void refresh();return()=>controller.current?.abort();},[refresh]);
 useEffect(()=>{if(phase!=='searching')return;const timer=setInterval(()=>setSearchSeconds(v=>v+1),1000);return()=>clearInterval(timer)},[phase]);
 useEffect(()=>{if(phase!=='accepting')return;const tick=()=>setCountdown(secondsUntil(match?.acceptDeadline));tick();const timer=setInterval(tick,250);return()=>clearInterval(timer)},[phase,match?.acceptDeadline]);
 useEffect(()=>{if(!['searching','accepting','ready','connecting','in_progress'].includes(phase))return;let timer:number|undefined;const schedule=()=>{if(document.hidden)return;timer=window.setTimeout(async()=>{await refresh();schedule();},['accepting','ready','connecting'].includes(phase)?1500:4000)};const visible=()=>{if(!document.hidden){if(timer)clearTimeout(timer);void refresh().finally(schedule);}else if(timer)clearTimeout(timer)};document.addEventListener('visibilitychange',visible);window.addEventListener('online',visible);schedule();return()=>{if(timer)clearTimeout(timer);document.removeEventListener('visibilitychange',visible);window.removeEventListener('online',visible)}},[phase,refresh]);
 const action=async(path:string,body:unknown={})=>{if(busy)return;setBusy(true);setError('');try{await request(path,{method:'POST',body:JSON.stringify(body)});await refresh();}catch(e){setError(e instanceof Error?e.message:'REQUEST_FAILED');}finally{setBusy(false)}};
 const toggleRegion=(v:string)=>setRegions(current=>{const n=current.includes(v)?current.filter(x=>x!==v):current.length<3?[...current,v]:current;if(!n.length)return current;localStorage.setItem('trust-regions',JSON.stringify(n));return n});const setPrimaryRole=(v:string)=>{setRole(v);localStorage.setItem('trust-primary-role',v)};
 const startSearch=async()=>{if(!config?.matchmaking?.enabled||!config.featureFlags.matchmaking_enabled?.enabled){setPhase('disabled');return}setPhase('loading');await action('/api/backend/queue/join',{ regions, primaryRole })};const cancelSearch=()=>void action('/api/backend/queue/cancel');const acceptMatch=()=>match&&void action(`/api/backend/matches/${match.id}/accept`);const declineMatch=()=>{if(match&&confirm('Decline this match? / Отклонить матч?'))void action(`/api/backend/matches/${match.id}/decline`)};const startConnection=()=>match&&void action(`/api/backend/matches/${match.id}/connection/start`);const connectionReady=()=>match&&void action(`/api/backend/matches/${match.id}/connection/ready`);const reset=()=>{setMatch(null);setPhase('idle')};
 return <MatchmakingContext.Provider value={{phase,match,regions,primaryRole,searchSeconds,acceptCountdown,busy,lastError,toggleRegion,setPrimaryRole,startSearch,cancelSearch,acceptMatch,declineMatch,startConnection,connectionReady,refresh,reset,resetDemo:reset}}>{children}<Overlay/></MatchmakingContext.Provider>}
export function useMatchmaking(){const c=useContext(MatchmakingContext);if(!c)throw new Error('useMatchmaking must be used inside MatchmakingProvider');return c}export function formatTime(s:number){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function Overlay(){const c=useMatchmaking();const {locale}=useLocale();const ru=locale==='ru';if(c.phase==='idle'||c.phase==='empty')return null;if(c.phase==='loading'||c.phase==='searching')return <Bar><Loader2 className="animate-spin motion-reduce:animate-none"/><b>{c.phase==='loading'?(ru?'Восстановление…':'Restoring…'):`${ru?'Поиск':'Searching'} · ${formatTime(c.searchSeconds)}`}</b><button onClick={c.cancelSearch}>{ru?'Отмена':'Cancel'}</button></Bar>;if(c.phase==='offline')return <Bar><WifiOff/><span>{ru?'Нет сети. Состояние восстановится автоматически.':'Offline. State will recover automatically.'}</span><button onClick={c.refresh}>{ru?'Повторить':'Retry'}</button></Bar>;if(!c.match)return <Bar><ShieldAlert/><span>{c.lastError||c.phase}</span><button onClick={c.refresh}>Retry</button></Bar>;const m=c.match;if(c.phase==='accepting')return <Modal live title={ru?'Матч найден':'Match Found'}><p className="text-center text-zinc-300">{m.roomCode||m.id} · {m.region||'—'} · {c.acceptCountdown}s · {m.accepted}/{m.required}</p><Teams match={m}/><button disabled={c.busy} onClick={c.acceptMatch} className="primary">{ru?'Принять':'Accept'}</button><button disabled={c.busy} onClick={c.declineMatch}>{ru?'Отклонить':'Decline'}</button></Modal>;if(c.phase==='ready'||c.phase==='connecting')return <Modal title={c.phase==='ready'?(ru?'Все подтвердили':'Everyone accepted'):(ru?'Готовность TRUST lobby':'TRUST lobby readiness')}><Teams match={m}/><Connections match={m}/><div className="flex flex-wrap gap-3"><button disabled={c.busy} className="primary" onClick={c.startConnection}>{ru?'Начать подключение':'Start connection'}</button><button disabled={c.busy} onClick={c.connectionReady}>{ru?'Я подключён':'I am connected'}</button><a href="steam://rungameid/570" className="rounded-xl border border-white/20 p-3"><Play className="inline"/> Dota 2</a></div><p className="text-sm text-zinc-400">{ru?'Проверяется готовность TRUST lobby; создание официального сервера Dota не подтверждено.':'TRUST lobby readiness is being checked; an official Dota server is not asserted.'}</p></Modal>;if(c.phase==='in_progress')return <Bar><Swords/><div><b>{ru?'Идёт матч':'In Progress'} · {m.roomCode} · {m.region}</b><p>{m.inProgressAt?formatTime(Math.max(0,Math.floor((Date.now()-new Date(m.inProgressAt).getTime())/1000))):'—'}</p></div></Bar>;if(c.phase==='completed')return <Result match={m} reset={c.reset} ru={ru}/>;if(c.phase==='cancelled')return <Modal title={ru?'Матч отменён':'Match cancelled'}><p>{m.cancellationReason||m.cancellationCode||'—'}</p><p>{m.requeued?(ru?'Вы возвращены в очередь':'Returned to queue'):(ru?'Вы не возвращены в очередь':'Not returned to queue')}</p><button className="primary" onClick={c.reset}>{ru?'Вернуться к очереди':'Back to queue'}</button></Modal>;return <Bar><ShieldAlert/><span>{c.lastError||c.phase}</span><button onClick={c.refresh}>Retry</button></Bar>}
function Bar({children}:{children:React.ReactNode}){return <div aria-live="polite" className="fixed bottom-4 left-1/2 z-[70] flex w-[calc(100%-2rem)] max-w-2xl -translate-x-1/2 items-center justify-between gap-3 rounded-2xl border border-white/10 bg-trust-panel/95 p-4 shadow-glow">{children}</div>}
function Modal({children,title,live=false}:{children:React.ReactNode;title:string;live?:boolean}){return <div className="fixed inset-0 z-[80] grid place-items-center overflow-y-auto bg-black/75 p-4"><section role="dialog" aria-modal="true" aria-live={live?'assertive':'polite'} className="my-auto grid max-h-[95vh] w-full max-w-4xl gap-5 overflow-y-auto rounded-3xl border border-white/10 bg-trust-panel p-5 shadow-glow"><h2 className="text-3xl font-black">{title}</h2>{children}</section></div>}
function Teams({match}:{match:MatchDetails}){return <div className="grid gap-4 md:grid-cols-2">{(['radiant','dire'] as const).map(side=><div key={side}><h3 className="mb-2 text-xl font-black capitalize text-trust-soft">{side}</h3>{match.teams[side].map(p=><div key={p.id} className="mb-2 flex items-center gap-3 rounded-xl bg-black/25 p-3"><img src={p.avatarUrl||'/avatar-fallback.svg'} alt="" className="h-9 w-9 rounded-full"/><span className="min-w-0 flex-1 truncate">{p.personaName}<small className="block text-zinc-400">{p.role}</small></span><b>{p.trustRating||'—'}</b><span>{p.acceptStatus}</span></div>)}</div>)}</div>}
function Connections({match}:{match:MatchDetails}){return <ul>{[...match.teams.radiant,...match.teams.dire].map(p=><li className="flex justify-between py-1" key={p.id}><span>{p.personaName}</span><span className={p.connectionStatus==='failed'?'text-rose-300':'text-zinc-300'}>{p.connectionStatus}</span></li>)}</ul>}
function Result({match,reset,ru}:{match:MatchDetails;reset:()=>void;ru:boolean}){const me=[...match.teams.radiant,...match.teams.dire].find(p=>p.id===match.currentPlayerId);const won=!!me&&me.team===match.winner;const delta=(a?:number,b?:number)=>a===undefined||b===undefined?'—':`${b-a>=0?'+':''}${b-a}`;return <Modal title={won?(ru?'Победа':'Victory'):(ru?'Поражение':'Defeat')}><p className="text-3xl font-black">Radiant {match.radiantScore??'—'} : {match.direScore??'—'} Dire</p><p>{ru?'Победитель':'Winner'}: {match.winner||'—'} · {ru?'Длительность':'Duration'}: {match.durationSeconds===undefined?'—':formatTime(match.durationSeconds)}</p>{me&&<div className="grid gap-2 sm:grid-cols-2"><p>TRUST Rating: {me.ratingBefore??'—'} → {me.ratingAfter??'—'} ({delta(me.ratingBefore,me.ratingAfter)})</p><p>Trust Score: {me.trustScoreBefore??'—'} → {me.trustScoreAfter??'—'} ({delta(me.trustScoreBefore,me.trustScoreAfter)})</p></div>}<p className="text-zinc-400">{ru?'Изменения рассчитаны сервером по результату матча и поведению.':'Changes are calculated by the server from match result and behavior.'}</p><button className="primary" onClick={reset}><RotateCcw className="inline"/> {ru?'Играть снова':'Play again'}</button></Modal>}
/* Legacy contract notes retained for migration tests:
 /api/backend/queue/status
 /api/backend/auth/guest
 const matchId = match.id; normalizeMatchDetails(details, matchId)
 data.players?.reduce; team === 'dire'; p.name || p.nickname
 localStorage.removeItem('trust-secondary-role'); localStorage.removeItem('trust-region');
 Server state now supersedes these legacy discovery calls.
*/
// `/api/backend/matches/${matchId}/accept`; `/api/backend/matches/${match.id}/decline`;
