'use client';
import Link from 'next/link';
import { LogOut, Menu, Shield, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useLocale } from '@/components/LocaleProvider';
type Account={steam?:{avatar?:string;personaName?:string};avatar?:string;personaName?:string;name?:string};
export function Nav(){
 const [open,setOpen]=useState(false); const [account,setAccount]=useState<Account|null>(null); const [state,setState]=useState<'loading'|'guest'|'offline'|'restricted'>('loading'); const {locale,setLocale,t}=useLocale();
 useEffect(()=>{fetch('/api/backend/me',{credentials:'include',cache:'no-store'}).then(async r=>{if(r.ok){setAccount(await r.json());setState('guest')}else setState(r.status===403?'restricted':r.status===503?'offline':'guest')}).catch(()=>setState('offline'));},[]);
 async function logout(){await fetch('/api/backend/auth/logout',{method:'POST',credentials:'include'});setAccount(null);setState('guest');window.location.href='/';}
 const steam=account?.steam||{avatar:account?.avatar,personaName:account?.personaName||account?.name}; const name=steam?.personaName; const avatar=steam?.avatar;
 const links=[['/#queue',t('queue')],['/leaderboard',t('leaderboard')],['/#patch',t('patch')],['/profile',t('profile')]];
 return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-trust-black/80 backdrop-blur-2xl"><nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 md:px-8"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-trust-violet shadow-glow"><Shield size={22}/></span><span className="text-xl font-black tracking-[.25em]">TRUST</span></Link><div className="hidden items-center gap-6 text-sm md:flex">{links.map(([href,label])=><Link href={href} key={href}>{label}</Link>)}</div><div className="hidden items-center gap-3 md:flex">{state==='loading'?<span>{t('loading')}</span>:name?<><Link href="/profile" className="flex items-center gap-2"><img src={avatar} alt="" className="h-9 w-9 rounded-full"/><b>{name}</b></Link><button onClick={logout} aria-label={t('logout')}><LogOut/></button></>:<a href="/api/backend/auth/steam/start" className="rounded-full bg-white px-5 py-2 text-sm font-bold text-trust-black">{state==='offline'?t('offline'):state==='restricted'?t('restricted'):t('signIn')}</a>}<button onClick={()=>setLocale(locale==='en'?'ru':'en')} className="rounded-full border border-trust-soft/30 px-3 py-2 text-xs font-black text-trust-soft">{locale.toUpperCase()}</button></div><button className="md:hidden" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></nav>{open&&<div className="grid gap-3 border-t border-white/10 p-4 md:hidden">{links.map(([href,label])=><Link onClick={()=>setOpen(false)} href={href} key={href}>{label}</Link>)}<a href="/api/backend/auth/steam/start">{t('signIn')}</a><button onClick={()=>setLocale(locale==='en'?'ru':'en')}>{t('language')}</button></div>}</header>;
}
