export const en = {
  queue: 'Queue', leaderboard: 'Leaderboard', patch: 'Patch', profile: 'Profile', signIn: 'Sign in through Steam', logout: 'Logout',
  loading: 'Loading…', offline: 'Backend offline', steamUnavailable: 'Steam unavailable', sessionExpired: 'Session expired', restricted: 'Account restricted',
  heroTitle: 'Competitive Dota 2 with verified trust.', heroText: 'Choose up to three regions and one role to join server-side TRUST matchmaking.', play: 'Play', liveQueue: 'Live queue',
  regionRole: 'Regions & role', regions: 'Regions', selected: 'Selected {count}/3', minimumRegion: 'Select at least one region.', role: 'Preferred role', matchmaking: 'Matchmaking', ready: 'Ready', searching: 'Searching…', cancel: 'Cancel search',
  matchFound: 'Match Found', acceptIn: 'Accept in {seconds}s', accept: 'Accept', decline: 'Decline', tryAgain: 'Please try again later.', account: 'Steam account', trustRating: 'TRUST rating', trustScore: 'Trust Score', registered: 'Registered', restrictions: 'Active restrictions', history: 'Match history', noMatches: 'No matches yet.', noRestrictions: 'No active restrictions.', logoutAll: 'Logout all devices', steamProfile: 'Open Steam profile', preferences: 'Preferences',
  playersAccepted: '{count, plural, one {# player accepted} other {# players accepted}}', language: 'Русский', patchTitle: 'Active TRUST Patch', steamPlayer: 'Steam player', clientErrorTitle: 'Something went wrong', clientErrorMessage: 'The page could not be displayed. Please reload and try again.', reload: 'Reload'
} as const;
export type TranslationKey = keyof typeof en;
export const ru: Partial<Record<TranslationKey, string>> = {
  queue:'Очередь',leaderboard:'Лидерборд',patch:'Патч',profile:'Профиль',signIn:'Войти через Steam',logout:'Выйти',loading:'Загрузка…',offline:'Backend недоступен',steamUnavailable:'Steam недоступен',sessionExpired:'Сессия истекла',restricted:'Аккаунт ограничен',heroTitle:'Соревновательная Dota 2 с проверенным доверием.',heroText:'Выберите до трёх регионов и одну роль для серверного матчмейкинга TRUST.',play:'Играть',liveQueue:'Текущая очередь',regionRole:'Регионы и роль',regions:'Регионы',selected:'Выбрано {count}/3',minimumRegion:'Выберите хотя бы один регион.',role:'Предпочитаемая роль',matchmaking:'Матчмейкинг',ready:'Готово',searching:'Поиск…',cancel:'Отменить поиск',matchFound:'Матч найден',acceptIn:'Принять за {seconds} с',accept:'Принять',decline:'Отклонить',tryAgain:'Попробуйте позже.',account:'Аккаунт Steam',trustRating:'Рейтинг TRUST',trustScore:'Trust Score',registered:'Дата регистрации',restrictions:'Активные ограничения',history:'История матчей',noMatches:'Матчей пока нет.',noRestrictions:'Активных ограничений нет.',logoutAll:'Выйти на всех устройствах',steamProfile:'Открыть профиль Steam',preferences:'Настройки',playersAccepted:'{count, plural, one {Принял # игрок} few {Приняли # игрока} many {Приняли # игроков} other {Приняли # игрока}}',language:'English',patchTitle:'Активный патч TRUST',steamPlayer:'Игрок Steam',clientErrorTitle:'Что-то пошло не так',clientErrorMessage:'Не удалось отобразить страницу. Перезагрузите её и попробуйте снова.',reload:'Перезагрузить'
};
